#BUIL VUE PROJECT (build stage)
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#CREATE NGINX SERVER (production build)
FROM nginx:stable-alpine as production-stage
RUN mkdir /app
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /app
CMD [ "nginx", "-g", "daemon off;" ]