#BUIL VUE PROJECT (build stage)
FROM node:lts-alpine as build-stage
RUN mkdir -p /frontend
WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

#CREATE NGINX SERVER (production build)
FROM nginx:stable-alpine as production-stage
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /frontend/dist /usr/share/nginx/html
CMD [ "nginx", "-g", "daemon off;" ]