version: '3.7'
services:
  oasip:
    image: frontendimg
    container_name: frontend
    networks: 
      - oasip-network
    restart: always
    environment:
      TZ: "Asia/Bangkok"
    
networks:
  oasip-network:
    external:
     name: oasip-network