version: '3.7'
services:
  oasip:
    build: ./
    image: oasip
    container_name: frontend
    ports:
      - 80:80
    networks: 
      - oasip-network
    restart: always
    environment:
      TZ: "Asia/Bangkok"
    
networks:
  oasip-network:
    external:
     name: oasip-network