version: '3.7'
services:
  db: 
    container_name: dbevents
    image: mysql:latest
    expose:
      - "3306"
    volumes:
      - ./Database/events.sql:/docker-entrypoint-initdb.d/events.sql
      - ./Database/mysql-data:/var/lib/mysql
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=1414
    restart: unless-stopped
    networks: 
      - oasip-network
  
  backend:
    build: ./BackEnd
    image: backendimg
    container_name: backend
    expose:
      - "8080"
    environment:
      - host_db=db
    restart: on-failure
    networks: 
      - oasip-network
     
  frontend:
    build: ./FrontEnd
    image: frontendimg
    container_name: frontend
    ports:
      - 3000:80
    restart: always
    volumes:
      - ./FrontEnd/conf.d/conf.conf:/etc/nginx/conf.conf
    networks: 
      - oasip-network

  revers_proxy:
    container_name: revers_proxy
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./FrontEnd/proxyconf.d/revers_proxy.conf:/etc/nginx/revers_proxy.conf
    depends_on:
      - frontend
    ports:
      - "80:80"
    networks: 
      - oasip-network

networks:
  oasip-network:
    external:
     name: oasip-network



