# FROM maven AS build
# RUN mkdir -p /backend
# WORKDIR /backend
# COPY pom.xml /backend
# COPY  src /backend/src
# RUN mvn -f pom.xml clean
# RUN mvn install -DskipTests

# FROM openjdk:17
# COPY --from=build /backend/target/*.jar app.jar
# EXPOSE 8080
# ENTRYPOINT ["java","-jar","app.jar"]

FROM openjdk:17 as build
WORKDIR /workspace/app
COPY ./mvnw .
COPY ./.mvn .mvn
COPY ./pom.xml .
COPY ./src src
RUN ./mvnw install -DskipTests

FROM openjdk:17
VOLUME /tmp
ARG APP=/workspace/app/target
COPY --from=build ${APP}/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]


# FROM openjdk:17-jdk-slim
# ARG JAR_FILE=./target/*.jar
# COPY ${JAR_FILE} app.jar
# ENTRYPOINT ["java", "-jar", "/app.jar"]