version: '3.7'
services:
  backend:
    build: ./
    image: backendimg
    container_name: backend
    networks: 
      - oasip-network
    restart: always
    environment:
      TZ: "Asia/Bangkok"

networks:
  oasip-network:
    external:
     name: oasip-network