version: '3.7'
services:
  reverse_proxy:
    image: node:lts-alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
    networks: 
      - oasip-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

networks:
  oasip-network:
    external:
     name: oasip-network
    

