version: '3.7'
services:
  reverse_proxy:
    image: nginx
    container_name: SSL_reverse_proxy
    ports:
      - "80:80"
    networks: 
      - oasip-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/:/etc/nginx/ssl:ro
    restart: on-failure

networks:
  oasip-network:
    external:
     name: oasip-network