version: '3.3'
services:
dbevents: 
    container_name: dbevents
    image: mysql
    ports:
      - 3306:3306
    networks: 
      - oasip-network
    volumes:
      - ./Database/events.sql:/docker-entrypoint-initdb.d/events.sql
      - ./Database/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1414
    restart: always
    
networks:
  oasip-networks:
    external:
     name: oasip-network