version: '3.7'
services:
  dbevents: 
    container_name: dbevents
    image: mysql
    ports:
      - 3306:3306
    networks: 
      - oasip-network
    volumes:
      - ./events.sql:/docker-entrypoint-initdb.d/events.sql
      - ./mysql-data:/var/lib/mysql
    environment:
      - TZ: Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=1414
    restart: always

networks:
  oasip-network:
    external:
     name: oasip-network